// <auto-generated />
using Blazor.Shared.Entities.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.Presentation.Server.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20221203190719_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blazor.Shared.Entities.Models.CarouselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_carousel_item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_alt");

                    b.Property<string>("Caption")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_caption");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_src");

                    b.HasKey("Id");

                    b.ToTable("CarouselItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "First image",
                            Caption = "First image",
                            Src = "images/carousel/image-01.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Alt = "Second image",
                            Caption = "Second image",
                            Src = "images/carousel/image-02.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Alt = "Third image",
                            Caption = "Third image",
                            Src = "images/carousel/image-03.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Alt = "Fourth image",
                            Caption = "Fourth image",
                            Src = "images/carousel/image-04.jpg"
                        });
                });

            modelBuilder.Entity("Blazor.Shared.Entities.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_image");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarouselItemId")
                        .HasColumnType("int")
                        .HasColumnName("fk_carousel_item");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_safe_name");

                    b.Property<string>("UnsafeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_unsafe_name");

                    b.HasKey("Id");

                    b.HasIndex("CarouselItemId")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarouselItemId = 1,
                            SafeName = "adhdwe.jpg",
                            UnsafeName = "image-01.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CarouselItemId = 2,
                            SafeName = "cxjuad.jpg",
                            UnsafeName = "image-02.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CarouselItemId = 3,
                            SafeName = "ioyweq.jpg",
                            UnsafeName = "image-03.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CarouselItemId = 4,
                            SafeName = "khfhew.jpg",
                            UnsafeName = "image-04.jpg"
                        });
                });

            modelBuilder.Entity("Blazor.Shared.Entities.Models.Image", b =>
                {
                    b.HasOne("Blazor.Shared.Entities.Models.CarouselItem", "CarouselItem")
                        .WithOne("Image")
                        .HasForeignKey("Blazor.Shared.Entities.Models.Image", "CarouselItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarouselItem");
                });

            modelBuilder.Entity("Blazor.Shared.Entities.Models.CarouselItem", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
