// <auto-generated />
using Blazor.Shared.Entities.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.Presentation.Server.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blazor.Shared.Entities.Models.CarouselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_carousel_item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_alt");

                    b.Property<string>("Caption")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_caption");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_src");

                    b.HasKey("Id");

                    b.ToTable("CarouselItems");
                });

            modelBuilder.Entity("Blazor.Shared.Entities.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_image");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarouselItemId")
                        .HasColumnType("int")
                        .HasColumnName("fk_carousel_item");

                    b.Property<string>("SafeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_safe_name");

                    b.Property<string>("UnsafeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_unsafe_name");

                    b.HasKey("Id");

                    b.HasIndex("CarouselItemId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Blazor.Shared.Entities.Models.Image", b =>
                {
                    b.HasOne("Blazor.Shared.Entities.Models.CarouselItem", "CarouselItem")
                        .WithOne("Image")
                        .HasForeignKey("Blazor.Shared.Entities.Models.Image", "CarouselItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarouselItem");
                });

            modelBuilder.Entity("Blazor.Shared.Entities.Models.CarouselItem", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
